### ISSUE TITLE
Block field not yet themed 

### ISSUE THREAD

**Issue by TheEbolaDoc** [vednoc/onyx#10]
Hey @vednoc ! 
I hope you are having a great day! I just saw that the field which appears if you get contacted by someone the first time is not yet themed, for details see the [Picture](https://ptpb.pw/L8kD.png).

Anyways, feel free to make this a "wontfix" since this is really a minor issue :smiley: 

Greetings 
Chris

**Comment by vednoc** [comment]
Hey Chris!

I've been just fine, thanks for the warm words. I hope you're having a great day, too! :blush:

If you can still get the HTML code for that section, it should be possible to fix it though it might take a couple of tries. :smile: If you can't, then no worries. Eventually it'll get fixed.
