### ISSUE TITLE
Faded Text on Contact Selection

### ISSUE THREAD

**Issue by lucasbmeister** [vednoc/onyx#11]
Hi Vednoc!

MINOR issue here.

When you search for a contact, or just opens the new chat option, and use the arrow keys to navigate, the selected contact is highlighted in white and the text is set to a color very similar to the highlighted background causing it to be hard to read.

**Comment by vednoc** [comment]
Hey Lucas!

I was able to replicate it and it is now fixed. Really nice find, thank you!:smiley:
