### ISSUE TITLE
Heads-Up to the Stickers.

### ISSUE THREAD

**Issue by Aliyss** [vednoc/onyx#12]
Hey there @vednoc,

First of all thanks for the theme. Really enjoying it and customizing the css-stuff for my personal use.

Just Wanted to give a Heads-Up that stickers are new to WhatsApp.
So it would look really nice if the time-display could be fixed for that as well, since it is still green.

![image](https://user-images.githubusercontent.com/33941859/47608282-5e93e600-da2b-11e8-9455-6523460fc2c8.png)

Many Thanks in Advance and have a great week,
👋 Aliyss

**Comment by vednoc** [comment]
That is strange. Does it occur in the main chat area or somewhere else? Thanks for letting me know! :smiley:

**Comment by Aliyss** [comment]
Hi...

Ok here is some more info... This is how it looks in the main chat area...

![image](https://user-images.githubusercontent.com/33941859/47616952-33f56c00-dac3-11e8-9b37-fcb54d49f1d1.png)

HTML of Picture 1:
`<div class="vW7d1"><span></span><div class="_3_7SH _1rK-b message-out tail _2Xi8x"><span class="tail-container"></span><span class="tail-container highlight"></span><div class="_23Cyn _23bXh _3JaNE"><div class="_1OBta"><div class="_3v3PK _1SYeE"><img class="_22Mb1" draggable="false" src="blob:https://web.whatsapp.com/4ba552cb-609a-4ed6-afdb-444306ceda87"></div><div class="_2Ll5c"><div class="_1DZAH" role="button"><span class="_1ORuP"></span><span class="_3EFt_">15:34</span><div class="_32uRw"><span data-icon="msg-dblcheck" class=""><svg id="Layer_1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 15" width="16" height="15"><path fill="#92A58C" d="M15.01 3.316l-.478-.372a.365.365 0 0 0-.51.063L8.666 9.879a.32.32 0 0 1-.484.033l-.358-.325a.319.319 0 0 0-.484.032l-.378.483a.418.418 0 0 0 .036.541l1.32 1.266c.143.14.361.125.484-.033l6.272-8.048a.366.366 0 0 0-.064-.512zm-4.1 0l-.478-.372a.365.365 0 0 0-.51.063L4.566 9.879a.32.32 0 0 1-.484.033L1.891 7.769a.366.366 0 0 0-.515.006l-.423.433a.364.364 0 0 0 .006.514l3.258 3.185c.143.14.361.125.484-.033l6.272-8.048a.365.365 0 0 0-.063-.51z"></path></svg></span></div></div></div></div></div><span></span></div></div>`

HTML of Picture 2:
`<div class="vW7d1 _1nHRW"><span></span><div class="_3_7SH _1rK-b message-in tail"><span class="tail-container"></span><span class="tail-container highlight"></span><div class="_23Cyn _2Qk9x _23bXh _3JaNE"><div class="_2R8MP"><div class="_111ze color-12 _2lc14" role=""><span class="RZ7GO" role="button">User Name</span><span dir="auto" class="_3Ye_R _1wjpf _1OmDL">;*</span></div></div><div class="_1OBta"><div class="_3v3PK _1SYeE"><img class="_22Mb1" draggable="false" src="blob:https://web.whatsapp.com/60268519-0b04-4ce3-81dd-ef761e7a6702"></div><div class="_2Ll5c"><div class="_1DZAH"><span class="_1ORuP"></span><span class="_3EFt_">20:25</span></div></div></div></div><span></span></div></div>`

**Comment by vednoc** [comment]
Hi! Still no update on my end.

Thanks for providing the snippet, here is a piece of code that *might* be enough to solve this issue:

```css
/* Username background. */
._2R8MP {
  background-color: var(--dark) !important;
}
/* Time. */
._2Ll5c > ._1DZAH {
  background-color: transparent !important;
}
```

The username background might need to be changed to `._2R8MP > div` but that's as far as I can reconstruct the markup. You don't need to edit the source code, just paste it into this field and see if it solves the issue.

![image](https://user-images.githubusercontent.com/18245694/47617843-12e54900-dacc-11e8-929f-2093ccee6377.png)

**Comment by vednoc** [comment]
Hi @Pescovisck, that is really awesome, thanks! @Aliyss could you give me a confirmation that this works before I merge it in the master branch?

Slightly off-topic: Is this a WhatsApp beta feature? I tried to apply for it but it seems like there are no places left at the moment.

**Comment by Aliyss** [comment]
@vednoc @Pescovisck Sorry for the delay in testing...

**Works fine except for a minor issue.**
_If the sticker is the first sticker: It looks normal as seen._
![image](https://user-images.githubusercontent.com/33941859/47915482-501e5200-dea3-11e8-89f6-a8d1cd040c8f.png)

_If the sticker is the second or following a text: It has a background._
![image](https://user-images.githubusercontent.com/33941859/47915451-2fee9300-dea3-11e8-8edf-8ebd33f49bee.png)

**Comment by vednoc** [comment]
Hey @Aliyss, @Pescovisck! (Sorry for the ping.)

Check out the newest update and let me know what you guys think. Fixes are implemented in 3c8499a and 9140ea1 if you want to take a closer look and they should apply to both group and direct conversations.

**Comment by lfcjohn** [comment]
> @vednoc @Pescovisck Sorry for the delay in testing...
> 
> **Works fine except for a minor issue.**
> _If the sticker is the first sticker: It looks normal as seen._
> ![image](https://user-images.githubusercontent.com/33941859/47915482-501e5200-dea3-11e8-89f6-a8d1cd040c8f.png)
> 
> _If the sticker is the second or following a text: It has a background._
> ![image](https://user-images.githubusercontent.com/33941859/47915451-2fee9300-dea3-11e8-8edf-8ebd33f49bee.png)

Same issue here, when reply with the sticker, background color will retain. I believe it's the original design of web version as it has white color background as well.

**Comment by vednoc** [comment]
Here is how it looks on my side:

![image](https://user-images.githubusercontent.com/18245694/48575538-88e21080-e912-11e8-988d-dba43535a0c8.png)

![image](https://user-images.githubusercontent.com/18245694/48575617-b929af00-e912-11e8-8a43-71a2ceaf7472.png)

The reply one remains unchanged:

![image](https://user-images.githubusercontent.com/18245694/48575915-77e5cf00-e913-11e8-951c-e26126636bc7.png)

**Comment by Aliyss** [comment]
Yes. It works fine 👍 

In my opinion we can close the issue.

**Comment by vednoc** [comment]
Since it's been a few days, I'll close the issue now. Cheers everyone! :tada:

**Comment by Aliyss** [comment]
Hey @vednoc,
I would like to reopen this, since it concerns the stickers again.

![image](https://user-images.githubusercontent.com/33941859/49168503-ea08db80-f337-11e8-90d1-62c00f487e9e.png)


And the gif section too.

![image](https://user-images.githubusercontent.com/33941859/49168560-09a00400-f338-11e8-8f5a-8fc331ce69af.png)

Have a great day.
Aliyss
