### ISSUE TITLE
Unreadable Text when someone sends a contact

### ISSUE THREAD

**Issue by yurividal** [vednoc/onyx#16]
When someone sends a contact as attachment inside a conversation, the contact's name and number are unreadable, because are the same color as background.

![image](https://user-images.githubusercontent.com/8555749/48863479-a1d64000-edb0-11e8-903e-3a92810229bd.png)

![image](https://user-images.githubusercontent.com/8555749/48863470-9d118c00-edb0-11e8-9d83-e19e61ab4178.png)
(This is after selecting the text)

**Comment by vednoc** [comment]
Hi! Thanks for reporting this bug.

I couldn't replicate the behavior but I fixed a few other things along the way. If you could inspect element and give me the HTML snippet that changes the text color I'd probably be able to solve the issue otherwise it'll be solved eventually.

**Comment by yurividal** [comment]
@vednoc i saw the issue when a friend sent me 2 contacts at once, inside a chat. I thknk the snippet is this (not sure how to collect it)

![image](https://user-images.githubusercontent.com/8555749/48900821-992a4c00-ee3a-11e8-9bd5-41dd7dfed0ed.png)
