### ISSUE TITLE
Heads-Up to the Plus-Minus Symbol

### ISSUE THREAD

**Issue by Aliyss** [vednoc/onyx#17]
![image](https://user-images.githubusercontent.com/33941859/48997589-c2a3ea00-f150-11e8-8658-d639f1e520d4.png)

Hey @vednoc,

Me again. Wanted to ask if you could change the background or the text of the plus/minus symbols when uploading a photo. Minor detail.

Many Thanks in Advance,
Aliyss

**Comment by vednoc** [comment]
Hi again! :smile:

Seems like that button got broken again, I'll fix it in just a bit.

Thanks for reporting this issue, really appreciated. :smiley:
