### ISSUE TITLE
Accent Color for mentions

### ISSUE THREAD

**Issue by nick-michael** [vednoc/onyx#2]
Maybe this is just a personal preference, but I feel like mentions ("@person") should be displayed in the accented color. I've just added this to mine:
```
    .message-in .matched-mention,
    .message-out .matched-mention,
    .message-out .matched-mention .at-symbol {
        color: var(--accent) !important;
    }
```

**Comment by vednoc** [comment]
Sounds like a great idea! I'm not a part of any group at the moment but I'll most likely add it when I get a chance to test it. Thank you very much for the suggestion. :+1:

**Comment by nick-michael** [comment]
Awesome 😃 
Just a screenshot of the before and after:
![image](https://user-images.githubusercontent.com/9058133/43357609-478486c8-927c-11e8-95a6-feb6d4a11363.png)

**Comment by nick-michael** [comment]
Sounds good - nice work, love the theme!
