### ISSUE TITLE
Using this theme in Franz

### ISSUE THREAD

**Issue by richardcane** [vednoc/onyx#26]
Been using this theme on web for a while and it's amazing. 

I've just started using Franz which allows users to add their own styling for dark themes, tried applying this one and it doesn't seem to mesh too well in its current form. There's an existing dark theme https://github.com/bloodf/franz-dark-whatsapp which looks suspiciously like an older version of this one.

Wondering if anyone else has it working?

**Comment by vednoc** [comment]
I used to use Franz a year ago but never tried it with custom styles. Will give it another spin and see how things go.

The used theme in that repo is actually the theme I wrote, just the fairly outdated version.

**Comment by richardcane** [comment]
Just had a quick play around with this and got it working perfectly.

Perhaps unsurprisingly, all that needs to happen is that any userstyle variable substitution needs to be done manually (not super hard, just find and replace anything starting with `/*[[` from the list of vars at the top), then need to save the resultant css file as darkmode.css under the whatsapp recipe for Franz.

Not sure it's worth spending any more time trying to automate or anything tbh.

**Comment by SoyDiego** [comment]
Thabks @richardcane works perfectly :)
