### ISSUE TITLE
Uploads missing background color

### ISSUE THREAD

**Issue by AdamRichard21st** [vednoc/onyx#36]
Looks like this issue is similiar to #25. File uploads lacks the custom background color, check this out:
![image](https://user-images.githubusercontent.com/39578558/59149277-f1e1c080-89e9-11e9-97f4-4e649904d5e7.png)

By the way, thanks a lot for this theme, it's awesome!

**Comment by vednoc** [comment]
Oh, I fixed it last night and stashed it away instead of committing the change. :sweat_smile: 

Thank you! Glad you find it useful. :tada:

**Comment by AdamRichard21st** [comment]
It seems to be lacking custom background color once again.
![image](https://user-images.githubusercontent.com/39578558/63197765-0fb54c80-c04f-11e9-97e0-ffb25cb319d5.png)
I hope it helps, thanks!

**Comment by UrielTapia** [comment]
I found the solution to be adding this code to the custom css directly. This issue is present as of today.

```
html[dir] ._3cukQ ._1mrMQ {
    background-color: var(--dark);
}
```
