### ISSUE TITLE
Make the link as anchor tag

### ISSUE THREAD

**Issue by SmartManoj** [vednoc/onyx#41]
![image](https://user-images.githubusercontent.com/7231077/62006245-93b89a80-b15b-11e9-85cd-549a85dfede8.png)

**Comment by vednoc** [comment]
It's impossible with CSS; one can only add cosmetic content to an element using pseudo-elements.

As a shortcut, try clicking on "Feedback" by opening customization menu for WhatsApp theme within Stylus popout, and it'll navigate you to the GitHub issues page.
