### ISSUE TITLE
Random spacing between messages

### ISSUE THREAD

**Issue by Virkkunen** [vednoc/onyx#43]
Sometimes between messages, a random sized space will appear, sometimes as small as one message bubble and other times as big as the whole window. It will disappear after scrolling the chat or changing conversations. Sending a message will sometimes remove this spacing, but many times it just glitches out making even more spaces until eventually coming back to normal.

An example:
https://i.imgur.com/19XPtEL.png
https://i.imgur.com/Tf8jko4.png

**Comment by vednoc** [comment]
That's quite odd. Does it happen when the theme is disabled?

**Comment by Virkkunen** [comment]
Only when it's enabled. 
Theme configurations also don't change anything (color, doodles, message tails...)
I currently use WhatsApp on Chrome, but I tested on Firefox and the same issue happens

**Comment by vednoc** [comment]
I've been trying to reproduce this issue for a little while in Firefox v68 and have no luck whatsoever.

If you know how to use DevTools, try to pick an element (shift + ctrl + c) of that bubble and see if it has some weird margin/padding added to it.

**Comment by Virkkunen** [comment]
Haven't been able to find anything out of the ordinary with devtools on Chrome. No weird padding or spacing, everything seems normal. It's also quite difficult to test it out since it happens randomly and doesn't last for long too.

To also rule it out, I'm not using any other extensions or themes on Stylus, my Chrome is solely dedicated to be used as a WhatsApp web window.

I'm thinking, could it be an issue with compact mode? I have no basis for this but I know compact mode has been rather glitchy since a few (whatsapp) updates back, for which I've also opened an issue here and you've fixed it.

**Comment by vednoc** [comment]
> I'm thinking, could it be an issue with compact mode?
It's plausible, but only in the case of second image. I'm still on the hunt for it to occur. :smile:

A few months ago I had something similar whenever the emoji/gif/stickers menu was open and closed, it was also very random and hard to reproduce. I'll add `help needed` and try again tomorrow.

**Comment by Virkkunen** [comment]
A quick update on this, I've disabled compact mode and ran it for some time, the issue has happened less frequently but it is still there, however now when I hover my mouse over the empty space created, it will disappear. 
Still can't find anything out of the ordinary when inspecting the page and elements.

**Comment by vednoc** [comment]
Hey @Virkkunen, I was wondering what's the status of this issue. I'm still unable to replicate the bug.

**Comment by Virkkunen** [comment]
Well, it hasn't resolved yet, and I've hard resetted both Firefox and Chrome, to no avail. I can't reproduce it on my other computer too, so I just learned to live with the issue. I'm just accepting that it's something really really specific that is happening in my computer that just started out of nowhere, and unfortunately I can't troubleshoot, there's really nothing out of the ordinary.
