### ISSUE TITLE
Message forward info header white

### ISSUE THREAD

**Issue by turbostar190** [vednoc/onyx#44]
After forwarding a message, open the info and look for forward counter. It's white with grey text.

![image](https://user-images.githubusercontent.com/24813315/64571716-00cb6c80-d365-11e9-9449-e37ac2a94fc7.png)

**Comment by vednoc** [comment]
I can't figure out how to reproduce this bug. Could you use DevTools to grab the selector applying the white color?

**Comment by turbostar190** [comment]
Classes with white `background-color` and shadows are `_1NZZN`, `_3XHR-` and the grey text is `_6xQdq _1w7vp`.
Anyway you can reproduce it forwarding a message and then watching stats of the forwarded message (right click, message info, scroll to the bottom).

**Comment by vednoc** [comment]
> Anyway you can reproduce it forwarding a message and then watching stats of the forwarded message (right click, message info, scroll to the bottom).

I did just that, doesn't show me the "forwarded" icon for some odd reason. :thinking: 

I'll add the hotfix for next update that will be out soon, feel free to close the issue if it ends up being resolved. :smiley:

**Comment by turbostar190** [comment]
> Anyway you can reproduce it forwarding a message and then watching stats of the forwarded message

Message in chat A forwarded to chat B, you have to see stats of message in chat B, not stats of forwarded message in chat A like I wrote before.

**Comment by vednoc** [comment]
> Message in chat A forwarded to chat B, you have to see stats of forwarded message in chat B, not stats of original message in chat A like I wrote before.

I found a couple of old ones in groups/DMs but they don't have stats on them, so I don't know what's up with it. Anyhow, the hotfix should work. :sweat_smile:
