### ISSUE TITLE
Chat bubble colors stay as default

### ISSUE THREAD

**Issue by dubcusb** [vednoc/onyx#49]
The speech bubbles in chat don't change with the colors I've defined. I have tried all settings and even tried to mess around with the CSS, but nothing seems to work.
![image](https://user-images.githubusercontent.com/21978144/65731193-2497ed80-e09b-11e9-86b2-99f75208a793.png)
I'm using the style avaliable when clicking "Install style" (?) on the README.md.

Edit: I used to use the old version (before 17th September), and now I've installed the style on a new machine with the latest update. Not sure if the version has anything to do with it.

**Comment by vednoc** [comment]
They broke it with their new update. I'll fix it shorty, but you'll have to update it manually to get the latest changes.

**Comment by vednoc** [comment]
Fixed in f26704d, just forgot to add a comment. :sleeping:

**Comment by dubcusb** [comment]
Oh my god thank you so much that was so quick! Really love this style and I appreciate your work on it!

**Comment by palisir** [comment]
Thanks for being so quick!

**Comment by pant03** [comment]
I'm afraid this is back with the newest update :(

**Comment by palisir** [comment]
Wouldn't it be possible to target the messages div by structure instead of "._Xxxxx" classes (like ._1lxsr) ?
