### ISSUE TITLE
timestamp in message list issue

### ISSUE THREAD

**Issue by Stanzilla** [vednoc/onyx#51]
![image](https://user-images.githubusercontent.com/75278/65907970-b1a5b400-e3c5-11e9-8a5f-7c396c723dff.png)

a bit hard to read here, might have been an issue I made when porting the stylesheet to franz though.

**Comment by vednoc** [comment]
I think it's a mistake on your end. Check in the browser if it's still present. If so, I'll investigate later today when I get a chance.

**Comment by Stanzilla** [comment]
Hrm just looked, the color is on the `._0LqQ` element and there is no code to change the color of them in Onyx.

**Comment by vednoc** [comment]
[This line] changes its colors. I did it that way so it doesn't break if they update the classes.

[0]: https://github.com/vednoc/onyx/blob/3c62b926a62da70bc89fd43f900ef1f9308dc2c4/WhatsApp.user.css#L431

**Comment by Stanzilla** [comment]
Oh interesting, that line was different here. Guess I missed that while porting the changes, sorry for the trouble!
