### ISSUE TITLE
[Franz] White bubble messages

### ISSUE THREAD

**Issue by MasterGeekMX** [vednoc/onyx#53]
Title says it. Since some time to now, the message bubbles are set to a white bacjground, but the text remain light gray, so it is very difficult to read the messages.

I tried to change the css file, trying out `--darker` or even `--dark` in Line 970, but it seems that it makes no effect.

![imagen](https://user-images.githubusercontent.com/10291989/66247430-04db7780-e6e2-11e9-8de0-d98871d338d3.png)

**Comment by vednoc** [comment]
Already fixed in f26704d06989a0818949b25724ffc60c5dd3a6b7.
