### ISSUE TITLE
Text unreadable again!

### ISSUE THREAD

**Issue by b2cbd** [vednoc/onyx#54]
Screenshot: https://imgur.com/mBUgDeX

**Comment by furai** [comment]
Yup, got the same after logging in today.

**Comment by hakan926** [comment]
Same here.

**Comment by SoyDiego** [comment]
> Just got home from uni. I'll fix it in just a bit.

Thanks for your work vednoc :)

**Comment by EudyM** [comment]
I just add this code and it works fine to me 

`html[dir] .message-in > div.tail > div,
  html[dir] .message-out > div.tail > div {
   background-color: #1f232a; 
  }

  html[dir] .message-in > div > div,
  html[dir] .message-out > div > div{
    background-color: #1f232a !important; 
  }

  html[dir] .message-in > div.tail > div > div > a > div {
    background-color: #2f3642 !important; 
  }`

**Comment by vednoc** [comment]
> Thanks for your work vednoc :)

Thanks for using my theme. :blush: 

> I just add this code and it works fine to me

Nice temporary fix, but I had to account for stickers and other things.

All in all, this is how they should've done it the last time, which to me looked like someone didn't know what they were doing and now they're fixing their mistakes. Now I'm gonna have to fix it for #38 as well, which *should* be out in a few days, at least for testing.

**Comment by furai** [comment]
Thanks for working on this! You're the boss!
