### ISSUE TITLE
Sent Audio Message Microphone Icon

### ISSUE THREAD

**Issue by KDASthenerd** [vednoc/onyx#55]
When sending audio messages, the microphone icon is fully white.
![image](https://user-images.githubusercontent.com/49505377/66520710-13e66f00-eac0-11e9-98e1-02ca0d026695.png)

The microphone is made in SVG, with two paths: one for the outline (with the same color as the message), and other for the microphone (with the accent color).
After messing with the CSS code, I found a solution:
![image](https://user-images.githubusercontent.com/49505377/66520817-41331d00-eac0-11e9-8703-013a61e62fb9.png)
I was able to use the code to change the color of each path fill.

Here's the code used to set the outer path to the message color:
`span:not([data-icon="image"]) > svg > path {
    fill: var(--darker) !important;
}`

Here's the code used to set the inner path to the accent color:
`span:not([data-icon="image"]) > svg > path:nth-child(2) {
    fill: var(--accent) !important;
}`

The second code uses "nth-child(2)" in order to not apply the accent color to the first path.

I'm finding it odd that this doesn't happen in every chat, and maybe this is an issue only I'm having. I tested it in a group, that consists of me alone. It looks like there are some lines in the Night Mode that make the mic outlines be transparent, and it fails to load or act on the group, so I end up with a fully white mic.

**Comment by vednoc** [comment]
It would be far better to reset the icon itself so it doesn't cause conflicts with other icons that have multiple paths. Something along the lines of:
```css
[data-icon ^= 'ptt-'] path:first-child { fill: crimson }
[data-icon ^= 'ptt-'] path:last-child { fill: tan }
```

I'll troubleshoot and probably fix it tomorrow. There is already have some code for it written in v2.
