### ISSUE TITLE
Quick replies unreadable in WA Business

### ISSUE THREAD

**Issue by tinyCoder32** [vednoc/onyx#56]
Hi, if you type a slash "/" to use quick replies, the text is unreadable.

<img width="585" alt="image" src="https://user-images.githubusercontent.com/17817239/66521986-08fa0180-eaf5-11e9-8435-19a8b29891c1.png">

Keep up the good work!

**Comment by vednoc** [comment]
I don't use WA Business so I'm unable to test it. Would be nice if you could copy/paste the markup. :smiley:

**Comment by tinyCoder32** [comment]
Of course:

```
html[dir] ._1omcu._2saG0 {
    background-color: var(--dark) !important;
}
```

<img width="934" alt="image" src="https://user-images.githubusercontent.com/17817239/66528987-5a60bb80-eb0a-11e9-8015-c40d6f102d7a.png">

Thanks.

**Comment by vednoc** [comment]
Thanks! I'll take a closer look at it tomorrow.
