### ISSUE TITLE
Suggestion: Different colors for message-in\message-out

### ISSUE THREAD

**Issue by E-RELevant** [vednoc/onyx#60]
Whatsapp, as well as any other chat system out there, make a visual difference between the person using the chat and the person they are talking to. It's sad to see that using 'onyx' disables this option.
My suggestion (the colors are just an example):
![image](https://user-images.githubusercontent.com/20738487/68475263-52428b80-0230-11ea-8053-322eb74c74eb.png)

**Comment by vednoc** [comment]
This was something I overlooked and forgot about for quite a while. You can try installing the #38 to see what it looks like. :smiley:

**Comment by E-RELevant** [comment]
> This was something I overlooked and forgot about for quite a while. You can try installing the #38 to see what it looks like. 😃

It seems that while version 1.99 has color differences and is definitely more suited to the vanilla design, the change is minor and does not allow for an unequivocal distinction.
![image](https://user-images.githubusercontent.com/20738487/68495939-e37a2800-0259-11ea-9087-6534f24bc3c5.png)

For my opinion the yellow-orange tones of the dates and loading do not match the color palette.

Furthermore, there seems to be a visual bug with the quotes right now, with the text remaining dark.
![image](https://user-images.githubusercontent.com/20738487/68496114-453a9200-025a-11ea-9a66-969fe09e56c6.png)

Crazy idea that came up to me and I think that could significantly improve usage: is there any way for the user to decide on the colors they want to display? So future updates will keep the braces of your choice too.

**Comment by vednoc** [comment]
> Furthermore, there seems to be a visual bug with the quotes right now, with the text remaining dark.

I thought I already fixed them, guess not. :thinking: 


> [...] is there any way for the user to decide on the colors they want to display?

You can already do it. Just click Stylus icon, then click on the gear icon and customize anything you want. There will also be an option to choose custom colors for bubbles, I just have to implement it.

**Comment by E-RELevant** [comment]
> [...] You can try installing the #38 to see what it looks like. 😃

A visual bug in v2 - a message with a link data:
![image](https://user-images.githubusercontent.com/20738487/68505279-7d000480-026f-11ea-8904-79cc4d7d336a.png)

**Comment by E-RELevant** [comment]
Another visual bugs using search option in a chat:

1. "Search for mesages with..." text
![image](https://user-images.githubusercontent.com/20738487/69367613-44195400-0ca1-11ea-8acb-f75f814bf2a0.png)

2. Loading animation
![image](https://user-images.githubusercontent.com/20738487/69367902-cd308b00-0ca1-11ea-85fa-068ba1fb025e.png)

3. Hovering a result will not highlight the message & there's only a top divider
![image](https://user-images.githubusercontent.com/20738487/69367833-ad996280-0ca1-11ea-8340-e63a69ec6cf4.png)

**Comment by vednoc** [comment]
> A visual bug in v2 - a message with a link data

Is this still present on your end?

> Loading animation

I'm not sure which color to use. So far, I've been replacing default WA colors with theme colors.

---

Will be fixing other things shortly, as well as missing parts in #59. Thank you for testing the rewrite, and for reporting bugs. :blush:

**Comment by E-RELevant** [comment]
> Is this still present on your end?

Not at all. the data-link works just fine.

> I'm not sure which color to use. So far, I've been replacing default WA colors with theme colors.

I think that all of the green ones should be a pale version of the 'Accent'\\'Blue' theme color.

> Will be fixing other things shortly, as well as missing parts in #59. Thank you for testing the rewrite, and for reporting bugs. 😊

Thank you very much!

Just a few more questions:

1. It seems like when installing the current version from https://userstyles.org/ it does not have the 'Configure' option.
![image](https://user-images.githubusercontent.com/20738487/69416740-ee37c100-0d1f-11ea-9c8e-77be6af28fa2.png)

2. Installing the script from the github library does not seem to have push updates, making me to go **manually** through the git-library and to find the correct new, updated, version to install. Both for v1 & v2 of the style.
![image](https://user-images.githubusercontent.com/20738487/69417121-b8470c80-0d20-11ea-8c51-56f81b05cb7b.png)

**Comment by vednoc** [comment]
> It seems like when installing the current version from https://userstyles.org/ it does not have the 'Configure' option.

The configuration is done through their website. Bad design, I'd say don't use it unless you have to.

 
> Installing the script from the github library does not seem to have push updates, making me to go manually through the git-library and to find the correct new, updated, version to install. Both for v1 & v2 of the style.

It auto-updates whenever `@version` field in the metadata is increased. If you modify the source code, the auto-update stops so it doesn't overwrite your changes. It should be working if you reinstall the v1, meanwhile while developing v2 I'm haven't been bumping the version so you had to reinstall manually whenever I fixed things.
