### ISSUE TITLE
Moving background image to this repo

### ISSUE THREAD

**Issue by TwentyFourMinutes** [vednoc/onyx#62]
This might have a valid reason, but I just noticed that the background image is linked to a discord upload: `https://media.discordapp.net/attachments/310799529161129984/417408747812552715/zilesanamin.jpg`
Is there any reason for it? I would rather move it to this repo for a cleaner look ;)

**Comment by vednoc** [comment]
Another thing I overlooked and forgot about. :sweat_smile:

**Comment by vednoc** [comment]
Will be live in tomorrow's update.
