### ISSUE TITLE
Message content/timestamp overlapping for people in Vietnam

### ISSUE THREAD

**Issue by JustDragon** [vednoc/onyx#67]
I have this overlapping problem if my phone is using Vietnamese language. If I change my phone language to English, it will fix problem.

**Comment by vednoc** [comment]
> If I change my phone language to English, it will fix problem.

Recently they added language-specific empty width at the end of every message.

I tried to change the language of my phone to Vietnamese, unfortunately I can't figure out which alphabet is which, and there are many are quite alike. :frowning: 

If you open DevTools and look at the `html` element, does it have `lang="vn"` as one of its attributes?

**Comment by JustDragon** [comment]
I don't see any lang="vn" when open DevTools. Vietnamese should be called Tiếng Việt on your phone.

**Comment by vednoc** [comment]
Looks like they added a fallback width value on the version `0.3.9308` of web app. It appears they use 'vi' instead of 'vn', and you can install new version from [this link](https://gitlab.com/vednoc/onyx/raw/master/WhatsApp.user.css).

**Comment by JustDragon** [comment]
It seem now whatsapp already fix this problem. Thank you for taking your time looking into this.
