### ISSUE TITLE
Contact field not dark

### ISSUE THREAD

**Issue by TheEbolaDoc** [vednoc/onyx#7]
Hey, its me again :blush: 

the field for linking contacts is still white, see the [screenshot](https://ptpb.pw/Puho.png).

Apart from that I still love your theme; it is converging towards perfection :heart: 

Greetings 
Chris

**Comment by vednoc** [comment]
Happy to see you again! :smiley:

It's fixed now, thanks for reporting the bug and for loving the theme, it's so nice to hear that. :heart:

It's pretty complete for the time being. Minor things from their updates can be fixed easily, so let's hope they don't introduce some major things all at once.
