### ISSUE TITLE
Users media files in groups

### ISSUE THREAD

**Issue by tinyCoder32** [vednoc/onyx#8]
Hi, of course, I should also say it again that i'm impressed with what you did.

There is something to consider fixing please:

![screen shot 2018-09-06 at 1 08 49 pm](https://user-images.githubusercontent.com/17817239/45151389-d3d6fd80-b1d6-11e8-85f9-db59e94b52b3.png)

Docs files and the download button.

Thank you so much for this perfect work!

**Comment by vednoc** [comment]
Thank you. :blush:

Weird. Could you use element picker to select the white element and give me the exact CSS snippet which sets the background color? To be 100% sure the snippet is correct, please modify `background` or `background-color` property to something else i.e. crimson to make sure the background changes before sending it to me.

This is what it looks like on my end.

![image](https://user-images.githubusercontent.com/18245694/45177570-9e043a00-b213-11e8-8adf-a0fc5fd453ea.png)

**Comment by tinyCoder32** [comment]
html[dir] .IKxkY ._12xX7 {
    background-color: #f2f2f2;
}

This is the class exactly responsible about the color.

**Comment by vednoc** [comment]
Update manually and feel free to close the issue if it's resolved. :blush:
