### ISSUE TITLE
Answer close button

### ISSUE THREAD

**Issue by TheEbolaDoc** [vednoc/onyx#9]
Hey there :)
I just wanted to let you know that the "answer close" button is still white, I dont know if you can fix this, so feel free to just close this issue :blush: 
https://ptpb.pw/6K-S.png
Greetings from Germany
Chris

**Comment by vednoc** [comment]
I noticed it yesterday but forgot to get back to it. :sweat_smile: It's resolved now, thank you so much for actively reporting issues. :heart:
